/*IDENTIFICO CONEXIONES ACTIVAS*/
SELECT spid, status, loginame, hostname, program_name
FROM SYS.sysprocesses
WHERE dbid = DB_ID('OptimaBank')

/*CERRAR CONEXIONES ACTIVAS*/
ALTER DATABASE OptimaBank SET MULTI_USER WITH ROLLBACK IMMEDIATE;

/*FORZAR CIERRE DE SESION SI FALLO EL PASO ANTERIOR*/
USE master;
GO
ALTER DATABASE OptimaBank SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE OptimaBank;